server:
  port: 8080  # Spring boot Server port

spring:
  h2:
    console:
      enabled: true  # H2 웹 콘솔을 사용하겠다는 의미
      path: /testdb

  datasource:
    driver-class-name: org.h2.Driver  #h2 드라이버 설정
    url: jdbc:h2:mem:testdb  #접속 URL
    username: sa  # 사용자 이름 (로그인 시 사용)
    password:  # 사용자 암호 (로그인 시 사용)# 콘솔의 경로

#  security:
#    oauth2:
#      client:
#        registration:
#          kakao:
#            client-id: X8m672khDWbTiYJlRBNwNGtH8K3k7HVE
#            redirect-uri: "http://localhost:8080/user/kakao/callback" # http://localhost:8080/login/oauth2/code/kakao
#            client-authentication-method: POST
#            authorization-grant-type: authorization_code
#            scope: profile_nickname, profile_image, account_email
#            client-name: Kakao
#        provider:
#          kakao:
#            authorization_uri: https://kauth.kakao.com/oauth/authorize
#            token_uri: https://kauth.kakao.com/oauth/token
#            user-info-uri: https://kapi.kakao.com/v2/user/me
#            user_name_attribute: id


  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        format_sql: true
logging.level:
  org.hibernate.SQL: debug