server:
  port: 8080  # Spring boot Server port

spring:
  h2:
    console:
      enabled: true  # H2 웹 콘솔을 사용하겠다는 의미

  datasource:
    driver-class-name: org.h2.Driver  #h2 드라이버 설정
    url: jdbc:h2:mem:testdb  #접속 URL
    username: sa  # 사용자 이름 (로그인 시 사용)
    password:  # 사용자 암호 (로그인 시 사용)# 콘솔의 경로

  reids:
    host:
      192.168.45.212
    port:
      6379


  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
logging.level:
  org.hibernate.SQL: debug

#  spring.redis.host=localhost
#  spring.redis.port=6379